apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240111001730.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240111001730.0.0+build.02e9424
  releaseNotes: |
    Release v20240111001730.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-01-2024-17-58-33-915164520/where-for-dinner-ui-my-apps-bundle@sha256:4eb0bd12672c94c766a81d26af53ef2816604797eac0111b5cba8951d1e5638f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

