apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240111001555.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240111001555.0.0+build.02e9424
  releaseNotes: |
    Release v20240111001555.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-10-01-2024-17-58-33-915164520/where-for-dinner-my-apps-bundle@sha256:a8c9b9333f6514a48b3aeca78f984f077d447bcabe606eaaa4419e24d7079f31
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

